# Hexo Configuration Hexo配置文件
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# 网站信息
title: 孤城落寞的博客                              #标题
subtitle: 记录学习的技能和遇到的问题                 #副标题
description: 做自己爱做的事，爱自己在做的事！         #网站描述
author: 孤城落寞                                  #作者昵称
language: zh-CN                                  #网站语言，默认英语，设置简体汉语
timezone: Asia/Shanghai                          #时区，默认电脑时区

# 网址设置
#如果网站是放在子目录中，将url设置成'http://yoursite.com/child'，将root设置成'/child/'
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.gclmit.club                          #网址
root: /                                                #网站根目录。如果网站是放在子目录中，将root设置成'子目录名'
enforce_ssl: true                                      #强制使用ssl
permalink: archives/:abbrlink.html                     #站点链接设置
abbrlink:                                              #站点链接设置
  alg: crc32  # 算法：crc16(default) and crc32
  rep: hex    # 进制：dec(default) and hex
  ## crc16 & hex
  ##  https://iassas.com/posts/66c8.html
  ## crc16 & dec
  ##  https://iassas.com/posts/65535.html
  ## crc32 & hex
  ##  https://iassas.com/posts/8ddf18fb.html
  ## crc32 & dec
  ##  https://iassas.com/posts/1690090958.html
permalink_defaults:

# Directory | 目录设置
source_dir: source        #资源文件夹，这个文件夹用来存放内容
public_dir: public        #公共文件夹，这个文件夹用于存放生成的站点文件
tag_dir: tags             #标签文件夹
archive_dir: archives     #归档文件夹
category_dir: categories  #分类文件夹
code_dir: downloads/code  #Include code 文件夹
i18n_dir: :lang           #国际化（i18n）文件夹            
#跳过指定文件的渲染，您可使用 glob 表达式来匹配路径,其中不需要渲染的文件夹或文件夹,放在[]中
# 这两个文件是百度和google的站长验证文件，不能渲染，否则会改变内容，不能验证过
skip_render: 
  - baidu_verify_R9MZjdMkXT.html
  - google0f8fac7da2b48ef8.html
  - README.md
  - 404.html
  - leancloud_memo.json

# Writing | 写作选项
new_post_name: :title.md                #新文章的文件名称
default_layout: post                    #预设布局
titlecase: false                        #把标题转换为 title case
external_link: true                     #在新标签中打开链接
filename_case: 0                        #把文件名称转换为 (1) 小写或 (2) 大写
render_drafts: false                    #显示草稿
post_asset_folder: false                #启动 Asset 文件夹
relative_link: false                    #把链接改为与根目录的相对位址
future: true                            #显示未来的文章
highlight:                              #代码块的设置
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Home page setting | 首页的分页设置
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator: #主页索引
  path: ''
  per_page: 5
  order_by: -date

archive_generator: #档案索引
  per_page: 20
  yearly: true
  monthly: true

tag_generator: #标签索引
  per_page: 10

# Category & Tag | 分类和标签
default_category: uncategorized      #默认分类
category_map:                        #分类别名
tag_map:                             #标签别名


# Date / Time format | 日期和时间格式
## Hexo uses Moment.js to parse and display date | Hexo 使用 Moment.js 来解析和显示时间。
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD       #日期格式
time_format: HH:mm:ss         #时间格式

# Pagination | 分页
## Set per_page to 0 to disable pagination
per_page: 10                   #每页显示的文章量 (0 = 关闭分页功能)
pagination_dir: page           #分页目录

# Extensions 
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
plugin: 
  - hexo-generator-feed
# 主题配置
theme: next

# 字数统计
symbols_count_time:
 #文章内是否显示
  symbols: true
  time: true
 # 网页底部是否显示
  total_symbols: false
  total_time: false

# leancloud_counter_security 统计配置
# 具体配置看 https://github.com/theme-next/hexo-leancloud-counter-security
leancloud_counter_security:
  enable_sync: true
  app_id: 
  app_key: 
  username: 
  password: 

# Deployment  | 部署配置
## Docs: https://hexo.io/docs/deployment.html
deploy:
  -
    type: git
    #repo: https://git.coding.net/gclm/gclm.git,master
    repo: 
       # 部署到github
       github: ,master
       # 部署到coding.net
       coding: ,master
  - 
    type: leancloud_counter_security_sync
